a--
SELECT D.NAME, COUNT(DST.NAME)
FROM DIVISION D, DISTRICT DST
WHERE D.NAME = DST.DIVISION_NAME
GROUPBY D.NAME;

b--
SELECT C.DISTRICT, COUNT(C.NID)
FROM CITIZEN C, DISTRICT DST
WHERE C.DISTRICT = DST.NAME
HAVING COUNT(C.NID) >= 20000
GROUPBY C.DISTRICT;

c--
SELECT COUNT(Accident_ID)
FROM CENTRAL_SYSTEM CS, CITIZEN C, DRIVING_LICENSE DL
WHERE C.NID = "210" AND C.LICENSE_ID = DL.LICENSE_ID AND
DL.LICENSE_ID = CS.LICENSE_ID;

d--
SELECT ROWNUM AS RANK, H.NAME
FROM(SELECT H.NAME, COUNT(A.ADMISSION_ID)
 FROM HOSPITAL H, ADMISSION A
 WHERE H.REG_ID = A.HOSPITAL_ID
 GROUPBY H.NAME)
WHERE ROWNUM <= 5;

e--
SELECT C.BLOOD_GROUP
FROM CITIZEN C, HOSPITAL H, ADMISSION A
WHERE C.NID = A.NID AND H.REG_ID = A.HOSPITAL_ID;

f--
SELECT D.NAME, TOTAL/D.SIZE
FROM(SELECT D.NAME, COUNT(C.NID) AS TOTAL
 FROM DIVISION D, CITIZEN C
 WHERE C.DIVISION = D.NAME
 GROUPBY D.NAME);

g--
SELECT DST.NAME
FROM(SELECT DST.NAME, TOTAL/DST.SIZE
 FROM(SELECT DST.NAME, COUNT(C.NID) AS TOTAL
 FROM DISTRICT DST, CITIZEN C
 WHERE C.DISTRICT = DST.NAME
 GROUPBY DST.NAME))
WHERE ROWNUM <= 3;

h--
SELECT DST.NAME, COUNT(CS.ACCIDENT_ID)
FROM DISTRICT DST, CITIZEN C, DRIVING_LICENSE DL, 
CENTRAL_SYSTEM CS
WHERE DST.NAME = C.DISTRICT AND C.LICENSE_ID = DL.LICENSE_ID 
AND DL.LICENSEID = CS.LICENSE_ID
GROUPBY DST.NAME;

i--
SELECT D.NAME
FROM(SELECT D.NAME, COUNT(CS.ACCIDENT_ID) AS ACCIDENT
 FROM DIVISION D, CITIZEN C, DRIVING_LICENSE DL, 
CENTRAL_SYSTEM CS
 WHERE D.NAME = C.DIVISION AND C.DRIVING_LICENSE = 
DL.LICENSE_ID AND
DL.LICENSE_ID=CS.LICENSE_ID
 GROUPBY D.NAME
 ORDERBY ACCIDENT)
WHERE ROWNUM <= 1;

j--
SELECT COUNT(CS.ACCIDENT_ID)
FROM DRIVING_LICENSE DL, CENTRAL_SYSTEM CS
WHERE DL.TYPE = "PROFESSIONAL" AND DL.TYPE = "NON PROFESSIONAL"
GROUP BY DL.LICENSE_ID;

k--
SELECT C.NAME
FROM(SELECT C.NAME, (A.RELEASE_DATE - A.ADMISSION_DATE) 
AS STAY
 FROM CITIZEN C, ADMISSION A
 WHERE C.NID = A.NID
 ORDERBY STAY DESC)
WHERE ROWNUM <= 1;

l--
SELECT D.NAME
FROM(SELECT D.NAME, COUNT(C.NID) AS TOTAL
 FROM DIVISION D, CITIZEN C
 WHERE D.NAME=C.DIVISION AND
GETDATE()-C.BIRTHDATE>= 15 AND GETDATE()-C.BIRTHDATE <= 30
 ORDERBY TOTAL)
WHERE ROWNUM <= 1;

m--
SELECT C.NAME
FROM CITIZEN C, DRIVING_LICENSE DL
WHERE C.LICENSE_ID = DL.LICENSE_ID AND GETDATE()>DL.EXPIRE_DATE;
n--
SELECT C.NAME, COUNT(CS.ACCIDENT_ID)
FROM CITIZEN C, DRIVING_LICENSE DL, CENTRAL_SYSTEM CS
WHERE C.LICENSE_ID = DL.LICENSE_ID AND DL.LICENSE_ID = 
CS.LICENSE_ID AND GETDATE()>DL.EXPIRE_DATE
GROUP BY C.NAME;

o--
SELECT C.NAME
FROM CITIZEN C, DRIVING_LICENSE DL
WHERE C.LICENSE_ID = DL.LICENSE_ID;
MINUS
SELECT C.NAME
FROM CITIZEN C, DRIVING_LICENSE DL, CENTRAL_SYSTEM CS
WHERE C.LICENSE_ID = DL.LICENSE_ID AND DL.LICENSE_ID = 
CS.LICENSE_ID;

p--
SELECT D.NAME, CS.DEATH
FROM DIVISION D, CITIZEN C, DRIVING_LICENSE DL, 
CENTRAL_SYSTEM CS
WHERE D.NAME = C.DIVISION AND C.LICENSE_ID = DL.LICENSE_ID 
AND DL.LICENSE_ID = CS.LICENSE_ID;

q--
SELECT C.NAME
FROM CITIZEN C, DRIVING_LICENSE DL
WHERE (DL.ISSUE_DATE -C.BIRTHDATE)<=22 OR (DL.ISSUE_DATE - C.BIRTHDATE)>=40;

r--
SELECT C.NAME
FROM CITIZEN C, DRIVING_LICENSE DL, CENTRAL_SYSTEM CS, 
ADMISSION A
WHERE C.LICENSE_ID = DL.LICENSE_ID AND DL.LICENSE_ID = 
CS.LICENSE_ID AND C.NID = A.NID AND CS.ACCIDENT_DATE_TIME = 
A.ADMISSION_DATE;
