CREATE USER s200042147 IDENTIFIED BY cse4308;
GRANT ALL PRIVILEGES TO s200042147;
CREATE TABLE STUDENT
(
ID NUMBER NOT NULL,
NAME VARCHAR2(50) NOT NULL,
DEPT_NAME VARCHAR2(50) nOT NULL,
TOT_CRED NUMBER NOT NULL
);

INSERT INTO STUDENT VALUES (00128, 'Zhang', 'Comp. Sci.', 102);
INSERT INTO STUDENT VALUES (12345, 'Shankar', 'Comp. Sci.', 32);
INSERT INTO STUDENT VALUES (19991, 'Brandt', 'History', 80);
INSERT INTO STUDENT VALUES (23121, 'Chavez', 'Finance', 110);
INSERT INTO STUDENT VALUES (44553, 'Peltier', 'Physics', 56);
INSERT INTO STUDENT VALUES (45678, 'Levy', 'Physics', 46);
INSERT INTO STUDENT VALUES (54321, 'Williams', 'Comp. Sci.', 5);
INSERT INTO STUDENT VALUES (55739, 'Sanchez', 'Music', 38);
INSERT INTO STUDENT VALUES (70557, 'Snow', 'Physics', 0);
INSERT INTO STUDENT VALUES (76543, 'Brown', 'Comp. Sci.', 58);
INSERT INTO STUDENT VALUES (76653, 'Aoi', 'Elec. Eng.', 60);
INSERT INTO STUDENT VALUES (98765, 'Bourikas', 'Elec. Eng.', 9);
INSERT INTO STUDENT VALUES (98988, 'Tanaka', 'Biology', 120);

SQL> SELECT ID,NAME FROM STUDENT;
SQL> SELECT NAME, DEPT_NAME FROM STUDENT WHERE TOT_CRED>100;
SQL> SELECT NAME, DEPT_NAME FROM STUDENT WHERE TOT_CRED BETWEEN 80 AND 120;
SQL> SELECT ID, NAME FROM STUDENT WHERE DEPT_NAME = 'Comp. Sci.';
SQL> SELECT NAME,TOT_CRED FROM STUDENT WHERE DEPT_NAME = 'Physics';
SQL> SELECT ID, NAME FROM STUDENT WHERE DEPT_NAME = 'Comp.Sci.' OR TOT_CRED<10;
SQL> SELECT DISTINCT DEPT_NAME FROM STUDENT;

