1--
SELECT COUNT(T.T_ID) AS TOTAL_T FROM TRANSACTIONS T WHERE T.A_ID=45;

2--
SELECT COUNT(T.TYPE) AS TOTAL_D FROM TRANSACTIONS T WHERE T.TYPE=1;

3--
SELECT A_ID,AMOUNT,TYPE FROM TRANSACTIONS WHERE EXTRACT(YEAR FROM TO_DATE(DTM, 'DD-MON-RR')) = 2020 ORDER BY DTM;

4--
SELECT A_ID,AMOUNT,TYPE FROM TRANSACTIONS;