1--
SELECT ACT_FIRSTNAME, ACT_LASTNAME
FROM ACTOR A, DIRECTOR D
WHERE (A.ACT_FIRSTNAME = D.DIR_FIRSTNAME) AND (A.ACT_LASTNAME = D.DIR_LASTNAME);

SELECT ACT_FIRSTNAME, ACT_LASTNAME
FROM ACTOR
intersect
SELECT DIR_FIRSTNAME, DIR_LASTNAME
FROM DIRECTOR;

2--
SELECT ACT_FIRSTNAME FIRSTNAME
FROM ACTOR
union all
SELECT DIR_FIRSTNAME
FROM DIRECTOR;

3--
SELECT DISTINCT MOV_TITLE TITLE
FROM MOVIE M, RATING R
WHERE (M.MOV_ID = R.MOV_ID) AND (R.REV_STARS IS NULL);

4--
SELECT avg(REV_STARS) REVIEW_AVERAGE
FROM RATING;

5--
SELECT A.MOV_TITLE, A.MIN_STAR
FROM (SELECT MOV_TITLE, min(REV_STARS) MIN_STAR
FROM RATING R, MOVIE M
WHERE M.MOV_ID = R.MOV_ID
GROUP BY MOV_TITLE) A
ORDER BY A.MIN_STAR DESC;

6--
SELECT ACT_LASTNAME LASTNAME, COUNT(REV_STARS) REVIEWS
FROM RATING, ACTOR, CASTS
WHERE ACTOR.ACT_ID = CASTS.ACT_ID AND CASTS.MOV_ID = RATING.MOV_ID
GROUP BY ACT_LASTNAME;

7--
SELECT ACTOR.ACT_LASTNAME, AVG(MOVIE.MOV_TIME) AS AVG_TIME
FROM CASTS JOIN ACTOR ON CASTS.ACT_ID = ACTOR.ACT_ID
JOIN MOVIE ON CASTS.MOV_ID = MOVIE.MOV_ID
JOIN DIRECTION ON CASTS.MOV_ID = DIRECTION.MOV_ID
JOIN DIRECTOR ON DIRECTION.DIR_ID = DIRECTOR.DIR_ID
WHERE DIRECTOR.DIR_FIRSTNAME NOT IN ('James') AND DIRECTOR.DIR_LASTNAME NOT IN
('Cameron')
GROUP BY ACTOR.ACT_LASTNAME;

8--
SELECT A.FIRSTNAME, A.LASTNAME, A.REVIEW_AVERAGE
FROM (SELECT *
FROM( SELECT D1.DIR_FIRSTNAME FIRSTNAME, D1.DIR_LASTNAME LASTNAME, 
MOV_TITLE, avg(REV_STARS) REVIEW_AVERAGE
FROM RATING R, DIRECTOR D1, DIRECTION D2, MOVIE M
WHERE (D2.MOV_ID = M.MOV_ID) AND (M.MOV_ID = R.MOV_ID) and
(D2.DIR_ID = D1.DIR_ID)
GROUP BY (D1.DIR_FIRSTNAME, D1.DIR_LASTNAME, MOV_TITLE))
ORDER BY REVIEW_AVERAGE DESC) A
WHERE ROWNUM <= 1;


9--
SELECT DISTINCT M.*
FROM MOVIE M, CASTS C, ACTOR A, (
SELECT ACT_ID ID
FROM ACTOR A, DIRECTOR D
WHERE (A.ACT_FIRSTNAME = D.DIR_FIRSTNAME) AND (A.ACT_LASTNAME = 
D.DIR_LASTNAME)
) X
WHERE (X.ID = C.ACT_ID) AND (C.ACT_ID = A.ACT_ID);

10--
ELECT A.*
FROM (SELECT MOV_TITLE, avg(REV_STARS) REVIEW_AVERAGE
FROM RATING R, MOVIE M
WHERE M.MOV_ID = R.MOV_ID
GROUP BY MOV_TITLE) A
WHERE A.REVIEW_AVERAGE > 7;


11--
SELECT A.MOV_TITLE, A.REVIEW_AVERAGE
FROM (SELECT MOV_TITLE, avg(REV_STARS) REVIEW_AVERAGE
FROM RATING R, MOVIE M
WHERE M.MOV_ID = R.MOV_ID
GROUP BY MOV_TITLE) A,
(SELECT AVG(REV_STARS) AVERAGE
FROM RATING) B
WHERE A.REVIEW_AVERAGE > B.AVERAGE;


12--
SELECT DISTINCT MOV_TITLE,(SELECT AVG(NVL(REV_STARS,0))
FROM RATING, MOVIE
WHERE MOVIE.MOV_ID = RATING.MOV_ID) AVERAGE
FROM MOVIE, RATING
WHERE MOVIE.MOV_ID = RATING.MOV_ID
ORDER BY MOV_TITLE;

13--
SELECT DISTINCT A1.ACT_ID ID, A1.ACT_FIRSTNAME FIRSTNAME, A1.ACT_LASTNAME
LASTNAME
FROM ACTOR A1, ACTOR A2
WHERE A1.ACT_GENDER='F' AND (A1.ACT_FIRSTNAME = A2.ACT_FIRSTNAME) AND
(A1.ACT_LASTNAME != A2.ACT_LASTNAME)
ORDER BY FIRSTNAME;

14--

